### ISSUE TITLE
Detect PWA?

### ISSUE THREAD

**Issue by cindro** [51Degrees/dotNET-Device-Detection#9]
Is there a way to detect if an app is PWA? alternatively is there a way to know if browser display is standalone?

**Comment by Steve51D** [comment]
Hi Cindro,

I've made some assumptions in my response below. Please let me know if I've got the wrong end of the stick.


Firstly, 'Progressive Web App' can mean different things to different people so I just want to differentiate between the two forms it can take:

1. Native app - a app downloaded to and running on the client device. e.g. the Twitter app.
2. Progressive web app - a website that looks like an app running on the device. e.g. the Twitter lite [website](https://mobile.twitter.com/)

Native apps are detected by the current device detection API (as long as they can be detected - e.g. the Facebook app), you can check this with the [IsWebApp](https://51degrees.com/resources/property-dictionary#IsWebApp) property.
Complicating this is the fact that a user clicking a link in the app may actually connect to your site via a standalone browser (e.g. chrome) rather than a browser within the app. If they are coming through the standalone browser then device detection will not be able to tell that the link was clicked within an app.

Web sites are more difficult. In this case, there are two ways a user on a third-party PWA could end up on your system:

1. Direct - The user's browser is connecting directly to your system either after being directed to by the PWA (e.g. to access a resource) or due to the user clicking a link. In either case, the request is coming from the device itself and the user-agent HTTP header that device detection relies on will not contain any details about the PWA. There may be a 'referrer' HTTP header or similar that can tell you the site the user came from.
2. Indirect - The PWA itself is requesting a resource on the user's behalf. In this case, you probably will not get any details from the actual user. It will just be a vanilla HTTP request. Again, device detection will not be able to tell you anything as it's just a request from the website's host.



As for standalone display mode, it doesn't look likely that the existing device detection API would be able to detect this as it's entirely client-side.
However, we are currently working on version 4 of the API and this includes the ability to more easily include information from the client-side so this is certainly a property that we could add in the future.

**Comment by Steve51D** [comment]
Hi Cindro,

Does the previous comment answer your question?
Just wondering if I can close this issue.

Thanks,
Steve.

**Comment by JoshGrew51D** [comment]
Closing this for the time being, please get back in touch and we will be happy to re-open
